### PR TITLE
Introduce an ADR for automatic base image version updates

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies
Related to https://github.com/thoth-station/kebechet/issues/991

## This introduces a breaking change

- No

## This Pull Request implements

Introduce an ADR to discuss about solutions for automatic updates of base image versions used to deliver container images.

### CODE REVIEW

**Comment by goern** [comment]
What will be the user interface? a github app? a bot appearing as @sesheta on github?

**Comment by mayaCostantini** [comment]
@goern This has not been decided yet, but we can discuss that today (cc @harshad16 , @KPostOffice) and see if a better solution could be to integrate this directly in AICoE-CI or as a Kebechet feature and thus provide a user interface.

**Comment by codificat** [comment]
/hold
based on the _WIP_ title. Please /unhold once it's ready for review

**Comment by goern** [comment]
actually sesheta should have added the wip label itself...

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Comment by goern** [comment]
/lgtm

please go ahead.

**Pull request merged**
