### PR TITLE
Make CronJob suspend configurable

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/thoth-station/cleanup-job/pull/35
Depends-On: https://github.com/thoth-station/graph-sync-job/pull/37
Depends-On: https://github.com/thoth-station/package-releases-job/pull/57

Blocked-By: https://github.com/thoth-station/cleanup-job/issues/29

### CODE REVIEW

**Comment by goern** [comment]
> only thing is that the other required files PR, also need to be merged.

@harshad16  which PR?

**Comment by harshad16** [comment]
@goern These PR contains the parameter declaration in the yaml files. 
https://github.com/thoth-station/graph-refresh-job/pull/51
https://github.com/thoth-station/graph-sync-job/pull/37
https://github.com/thoth-station/package-releases-job/pull/57
https://github.com/thoth-station/cleanup-job/pull/35

I don't know what happens if an `oc new-app` is given parameter but the parameters are not declared in the config yaml. :) Just to be safe we should merge these above PR's as well. 😃

**Comment by goern** [comment]
Ah right, looks like @fridex forgot some Depends-On in the PR description ;)

**Comment by goern** [comment]
Recheck

**Comment by fridex** [comment]
Looks like you had fun :) Anyone to review and hit the merge button?

**Comment by goern** [comment]
> Anyone to review and hit the merge button?

Ja, sesheta will add the "approved" label in a few cycles... or a human can add the label. If added, zuul will merge :) Actually, I dont know if it will merge the dependence too?! #letssee

**Comment by goern** [comment]
https://github.com/thoth-station/package-releases-job/pull/57 has been closed, this PR still depends on it, lets zee how zuul works thur that...

@TristanCacqueray

**Pull request merged**
