### PR TITLE
Add shreekarSS to thoth members

### PR DESCRIPTION
**Pull request by shreekarSS**
Signed-off-by: Shreekar <sshreeka@redhat.com>

## This introduces a breaking change

- Yes
- No

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by goern** [comment]
@shreekarSS please add yourself to the Dev team too ;)

**Comment by goern** [comment]
@shreekarSS please add yourself to the Dev team too ;)

**Comment by goern** [comment]
I just added/invited @shreekarSS manually to https://github.com/orgs/thoth-station/teams/devs/members

**Pull request merged**
