### PR TITLE
add a ARD to retire Qeb-Hwt

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
lgtm!

**Comment by goern** [comment]
/approve

@pacospace could you turn this into an issue so we can work on it? thx!!

/assign @pacospace

**Comment by pacospace** [comment]
> /approve
> 
> @pacospace could you turn this into an issue so we can work on it? thx!!
> 
> /assign @pacospace

Isn't it https://github.com/thoth-station/kebechet/issues/714?

**Comment by goern** [comment]
@pacospace ja right :)

**Pull request merged**
