### PR TITLE
pulp-repository-sync-job has been renamed

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by goern** [comment]
@fridex there is also https://github.com/thoth-station/core/blob/master/community/github-config.yaml#L1057 for ACL, pls change that too, thx.

**Comment by fridex** [comment]
> @fridex there is also https://github.com/thoth-station/core/blob/master/community/github-config.yaml#L1057 for ACL, pls change that too, thx.

I think that change is part of this PR:

https://github.com/thoth-station/core/blob/7164be5ede6a3e394da86195fa690bb0d27a43a1/community/github-config.yaml#L1057

**Comment by goern** [comment]
https://github.com/thoth-station/adviser/pull/1941 needs a change too

**Comment by goern** [comment]
> > @fridex there is also https://github.com/thoth-station/core/blob/master/community/github-config.yaml#L1057 for ACL, pls change that too, thx.
> 
> I think that change is part of this PR:
> 
> https://github.com/thoth-station/core/blob/7164be5ede6a3e394da86195fa690bb0d27a43a1/community/github-config.yaml#L1057

d'uh, ja sorry, did I say I'm sleepy this morning?!

**Pull request merged**
