### PR TITLE
proposing SIG docs

### PR DESCRIPTION
**Pull request by goern**
I started a sigs.yaml, so that we can structure and document what the SIGs are about, who is doing what. I follow the Kubernetes community as an example.

Some additional info at https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md

The goal is to create an info page that describes what a sig is about, and in the end, declare who is responsible for what components. This seems to be a crucial step to prepare for growth.

wdyt?

### CODE REVIEW

**Comment by xtuchyna** [comment]
So, all of the sigs are gonna be defined here in `sigs.yaml` ? Or should every repo have a `sig.yaml` with sigs that are related to it?

**Review by xtuchyna — COMMENTED** [review]
So, all of the sigs are gonna be defined here in sigs.yaml ? Or should every repo have a sig.yaml with sigs that are related to it?

**Comment by goern** [comment]
> So, all of the sigs are gonna be defined here in sigs.yaml ? Or should every repo have a sig.yaml with sigs that are related to it?

all of them go in this one file.

**Comment by fridex** [comment]
/lgtm

:+1:

**Pull request merged**
