### PR TITLE
Added the prometheus pushgateway host and port env vars 

### PR DESCRIPTION
**Pull request by hemajv**
Rebasing and merging all pull requests (PRs merged: #87, #90 , #91)
Added the prometheus pushgateway host and port env vars for:
- configmap-template
- provisions.yaml
- playbooks/roles/thoth-frontend/tasks/main.yaml
- playbooks/roles/thoth-middletier/tasks/main.yaml

### CODE REVIEW

**Comment by goern** [comment]
@hemajv handing over the ENV var to ansible (thats whats happening in this playbook) is not enough, you need to extend the roles too. @harshad16 can help you with that as he did it as one of his first tasks.

/lgtm

**Comment by hemajv** [comment]
Yes sure, Frido mentioned this as well. I will be making those changes too.

**Comment by goern** [comment]
recheck

**Comment by hemajv** [comment]
@goern I have now merged all the pull requests into this one (i.e. #88) and closed the others.

**Pull request merged**
