### PR TITLE
add release policy ADR

### PR DESCRIPTION
**Pull request by goern**
add ADR documenting our release policy

Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
We should also think about Thoth release information. If I talk to a Thoth deployment via API endpoints, I cannot obtain the cal version identifier of Thoth.

@harshad16 can we somehow easily include version identifier present in https://github.com/thoth-station/thoth-application/blob/master/version.py in user-api container image so that we can expose it in endpoints?

**Comment by harshad16** [comment]
> @harshad16 can we somehow easily include version identifier present in https://github.com/thoth-station/thoth-application/blob/master/version.py in user-api container image so that we can expose it in endpoints?

@fridex  will look into this, on getting the version into the container image .

**Comment by goern** [comment]
@fridex as you have created #609 can we merge this one?

**Review by fridex — APPROVED** [review]
:+1:

**Pull request merged**
