### PR TITLE
Removed TODO

### LINKED ISSUE #265: (spiffxp): is this required though?
https://github.com/thoth-station/core/blob/e9d606ffc0b9bf1c14e91ac68e8fb21a7e1eeb16/community/generator/app.go#L289-L294

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in e9d606ffc0b9bf1c14e91ac68e8fb21a7e1eeb16 when #263 was merged. cc @goern.

### PR DESCRIPTION
**Pull request by tlegen-k**
Removed unnecessary TODO from file according to issue #265. As it seems that these checkups are required.

closes #265

### CODE REVIEW

**Comment by goern** [comment]
@tlegen-k ping

**Comment by tlegen-k** [comment]
I think that merge conflict was resolved.
File version from the tide was chosen. Markers from file  community/generator/app.go  were removed.

**Comment by goern** [comment]
Hey @tlegen-k looks like its moving forward in the right direction. The remaining problem should be solvable, by running `pre-commit` on your local clone, install the git pre-commit hooks via `pre-commit install`, if you don't have `pre-commit` installed, use `sudo dnf install -y --nodocs pre-commit`

**Pull request merged**
