### PR TITLE
Feature: End-to-End Tests

### PR DESCRIPTION
**Pull request by goern**
This is the first iteration of End-to-End Tests, I cover reading the Result API. Tests use [Behave](http://behave.readthedocs.io/en/stable/index.html) and [Hamcrest](http://pyhamcrest.readthedocs.io/en/latest/tutorial/)

A BuildConfig for a container running the test is included, that container could be started via `oc delete pod core-e2e-test && oc run -ti core-e2e-test --image=core-e2e-test --restart=Never -- /opt/app-root/bin/behave --no-color`

Open Question: How to make this part of the CI?

### CODE REVIEW

**Comment by goern** [comment]
I'm good to go, let's merge it

**Comment by goern** [comment]
Not all the plugins are enabled :P

**Comment by fridex** [comment]
> Not all the plugins are enabled :P

No cute cats :cry:

**Pull request merged**
