### PR TITLE
HouseKeeping: Updated repos and teams for triaging

### PR DESCRIPTION
**Pull request by harshad16**
HouseKeeping: Updated repos and teams for triaging
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### Description
- Updated the missing repos in the listed.
- keep the honourary members are members and removed from teams.
- Allowed all public repo in thoth-station for triage for dev team
- Removed redundant teams

### CODE REVIEW

**Review by codificat — COMMENTED** [review]
One suggestion, and a question: this PR archives a few repos;  is it easy / possible / desirable to add final commits to them before archival?

**Comment by harshad16** [comment]
Seems like the prow, doesnt allow multiple deletions of team
so will remove only one, in this and other in another pr.

**Comment by harshad16** [comment]
Ready for review
I will fix the peribolos issue manually, seems like it doesn't allow deletion of teams in bluk

**Comment by codificat** [comment]
/approve

although, as you said, we might have to do the team deletion in separate PRs to keep peribolos happy?

**Comment by harshad16** [comment]
Thanks for the review, i will fix the issues manually.

**Pull request merged**
