### PR TITLE
Remove needs-triage label by default

### PR DESCRIPTION
**Pull request by codificat**
## Related Issues and Dependencies

https://github.com/thoth-station/thoth-application/issues/2359

## This introduces a breaking change

- Yes

Some repos have a `needs-triage` label in their issue templates.

This PR will remove that label from most of the repos, and this will result in that new issues created from these templates will get a comment complaining that the label does not exist.

If this happens on a certain repo, a PR should be sent there to update the issue templates. The ones from the template project already do not have that label and can be used as a model to update other repos.

## This Pull Request implements

Restrict the `needs-triage` label to be used only for repos where prow is managing it via its require matching label plugin.

### Description

The idea is that the `needs-triage` label is a user experience feature to help inform users of the lifecycle of an issue, thanks to the friendly message posted by the prow plugin when it adds the label.

The actual triage process is independent of the `needs-triage` label, and relies only on the various `triage/*` labels: an issue that does not have any `triage/foo` label needs triage.

### CODE REVIEW

**Comment by codificat** [comment]
Note: also including a fix for the path change in the `label_sync` image (ref https://github.com/kubernetes/test-infra/blob/198fd8ef3d2441af01a0fad802ec9809b162e599/prow/ANNOUNCEMENTS.md?plain=1#L195)

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
