### PR TITLE
Make myself an org admin

### PR DESCRIPTION
**Pull request by codificat**
This PR is to move myself from member to admin of the thot-station GitHub org.

### CODE REVIEW

**Comment by codificat** [comment]
hmm... peribolos is complaining about:

```json
{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:194",
  "func": "main.main",
  "level": "fatal",
  "msg": "Configuration failed: failed to configure thoth-station members: cannot delete 7 memberships or 0.333 of thoth-station (exceeds limit of 0.150)",
  "severity": "fatal",
  "time": "2022-11-30T23:20:29Z"
}
```

I'm not sure where these "7 memberships" deleted come from - I'm only moving (not even deleting) one from member to admin.

**Comment by goern** [comment]
/lgtm
let's ignore the peribolos complaint
/approve

**Comment by harshad16** [comment]
> I'm not sure where these "7 memberships" deleted come from - I'm only moving (not even deleting) one from member to admin.

I think that issue is coming from previous commit: https://github.com/thoth-station/core/commit/d152669bbc452a46cc9cc3b2e322308c7d992bd4

Anyhow i have manually added you as a OWNER of the group.
Maybe we would have to remove those members manually to fix peribolos.
Great way to check your privileges, you get to remove members ,if you wanna give it a try @codificat

**Comment by codificat** [comment]
> I think that issue is coming from previous commit: [d152669](https://github.com/thoth-station/core/commit/d152669bbc452a46cc9cc3b2e322308c7d992bd4)

Ah, good find.

> Anyhow i have manually added you as a OWNER of the group. Maybe we would have to remove those members manually to fix peribolos. Great way to check your privileges, you get to remove members ,if you wanna give it a try @codificat

good way to test! :smile:

Thanks for adding me. I have now manually removed the members referenced in that commit.

With that, this PR should now be ready for a
/retest

**Pull request merged**
