### PR TITLE
removed due to inactivity or migration to sesheta/

### PR DESCRIPTION
**Pull request by goern**
Depends-On: https://github.com/thoth-station/sesheta/pull/2

This is just a clean up...

### CODE REVIEW

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
so this will be merged if the dependency is merged.

**Comment by goern** [comment]
@fridex ping

**Comment by goern** [comment]
why is it not merging?!

**Comment by fridex** [comment]
@thoth-zuul[bot] merge! :angry:

**Comment by goern** [comment]
@fridex pls reapprove :)

**Pull request merged**
