### PR TITLE
New intern project - make release after PR merges

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Related to https://github.com/thoth-station/kebechet/issues/711#issuecomment-938564759

## This introduces a breaking change

- [ ] Yes
- [X] No
- 
## Description
Make intern project out of the "Release after PR merges" suggestion Issue

### CODE REVIEW

**Comment by KPostOffice** [comment]
Hey, I think I have already implemented this. I did not realize it was an intern project

**Comment by goern** [comment]
> Hey, I think I have already implemented this. I did not realize it was an intern project

any pointer to a demo or doc?

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/kebechet/blob/master/docs/managers/version.rst

Need to add it here. Demoing it today with the Keb tests

**Pull request closed without merging**
